default:
  golem_name: DashboardHelper
  golem_version: 0.0.0.9000
  app_prod: no
production:
  app_prod: yes
dev:
  golem_wd: \\datastores02/healthpubglobal/1887Building/Communicable Disease/COVID
    2019 Novel Coronavirus/Charts Graphs and Data/Sam/R Projects/DashboardHelper
